### ISSUE TITLE
Discord GIF scrolling causing black flashes

### ISSUE THREAD

**Issue by yippeeeyay** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#1054]
### Checklist [README]

- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [x] Application is not cracked

### Application [Required]

Discord

### Processor / Processor Number [Required]

Intel Core Ultra 7 155H

### Graphic Card [Required]

Intel Arc Graphics

### GPU Driver Version [Required]

32.0.101.6647

### Rendering API [Required]

DirectX11

### Windows Build [Required]

Windows 11 24H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/19268877/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- Search for any kind of gif on Discord
- Scroll for a few seconds and black flashes will occur at random intervals. The scrolling is also laggy.
- After a few black flashes and a decent bit of scrolling, the scrolling becomes smoother and the flashes stop.
Example:
https://youtu.be/pBh6jggXGKY
NOTE: Turning Hardware Acceleration off fixes the problem entirely and scrolling is smooth.

### Device / Platform

ASUS Zenbook 14 Q425MA

**Comment by Felipe-Intel** [comment]
Hello @yippeeeyay I'll be looking into this. I'd like to ask you a couple questions: 

1. is this happening with the Discord app, over the web browser or both? 
2. is it the entire screen that flashes or is it just the app/web browser? 

I'll try to replicate this issue. I'll keep you posted. 

By the way, we just release a new driver, 32.0.101.6651. Could you please test with [this version](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) on your end and let me know?

**Comment by yippeeeyay** [comment]
@Felipe-Intel Thank you for looking into this.
I have installed the new driver. I used DDU beforehand to make sure the driver was cleanly installed. However, the issue still persists.
This happens on both Chrome and the Discord app.

The black flashes will happen randomly while scrolling GIFs three times at maximum and then it becomes smooth. I noticed that after the three black flashes, if I check chrome://gpu/, it says Hardware Acceleration is disabled, when it was enabled before.

I have attached the chrome log. This is after the three black flashes occur. 

[about-gpu-2025-03-20T21-34-56-583Z.txt](https://github.com/user-attachments/files/19375962/about-gpu-2025-03-20T21-34-56-583Z.txt)

**Comment by Felipe-Intel** [comment]
Thanks. I was able to see the issue in a 155H platform. I will add your log to my report. 

I'll come back to you when I have news about this. 

In the meantime, if it is ok, use the workaround: turn hw accel off.

**Comment by Squall-Leonhart** [comment]
This is an ongoing Windows bug.

**Comment by yippeeeyay** [comment]
> This is an ongoing Windows bug, AMD and Nvidia also affected.
> 
> https://issues.chromium.org/issues/409086876

This is a driver regression. On 101.6083_101.5736 this issue is not present at all. You have to use the internet archive to download this old driver because it is no longer hosted on Intel's website https://web.archive.org/web/20241015005144/https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html

Disabling MPO as per the suggestions does not fix the issue on latest drivers.

However, changing the ANGLE backend in chrome://flags does solve the issue on latest drivers. Anything other than D3D11 works, with D3D9 and OpenGL rendering the gifs smoothly while D3D11on12 lags but does not have black screen flashes.

**Comment by kkrmpubg** [comment]
This seems to happen in steam app with gif profiles. same with my discord and browser. turning off hardware acceleration fixes it within the app and browser but scrolling feels sluggish when turned off.

**Comment by yippeeeyay** [comment]
As well as the last issue still being present, there is a new issue on the latest driver 32.0.101.6734 (WHQL Certified).
If you have Discord open on a page which is displaying GIFs (in my case I am in a DM with someone and have two GIFs on screen) and then minimize the app, if you wait 3 minutes and open the app, the entire screen will go black for 3 seconds and then come back. My windows ICC color profile gets reset too until I open the volume flyout, so I am assuming this is a full driver crash.

This is also reproducible in Chrome if you have a Discord tab open which is displaying GIFs and then leave it open in the background while you are on another tab and wait 3 minutes. Once you go back to the tab, the entire screen will go black for 3 seconds and then come back.

I have also had this happen while on X/Twitter on a thread which had multiple videos playing. Same black screen issue occurs after leaving the tab in the background for about 3 minutes. I couldn't reproduce it on X/Twitter as easily, so DIscord seems to be the best way to try and reproduce the problem.

I have attached the chrome://gpu log. Since this is different behavior from the original issue in this thread, I am willing to open a new issue if needed. I wonder if I should make a chromium thread on this problem as well?

[about-gpu-2025-04-18T03-53-53-379Z.txt](https://github.com/user-attachments/files/19807988/about-gpu-2025-04-18T03-53-53-379Z.txt)

**Comment by yippeeeyay** [comment]
> As well as the last issue still being present, there is a new issue on the latest driver 32.0.101.6734 (WHQL Certified). If you have Discord open on a page which is displaying GIFs (in my case I am in a DM with someone and have two GIFs which were sent in the chat on screen) and then minimize the app, if you wait 3 minutes and open the app, the entire screen will go black for 3 seconds and then come back. My windows ICC color profile gets reset too until I open the volume flyout, so I am assuming this is a full driver crash...

It seems this different issue was solved in the newest driver 32.0.101.6739 thankfully. However, the original issue of this thread, the black flashes (not entire screen but the Chrome/Discord window) while scrolling GIFs, persists.

**Comment by Karen-Intel** [comment]
Hey guys, looking through our forums I found that this issue is [not exclusive to Intel GPUs](https://community.intel.com/t5/Intel-ARC-Graphics/Discord-windows-app-experiencing-black-screens-when-in-the-gif/m-p/1669004/highlight/true#M21239). See below

![Image](https://github.com/user-attachments/assets/0d304ddd-1e77-4eb7-8657-b08f04d83f3e)

As the issue is related to Discord hardware acceleration, we will be closing this one out. Thank you for your time and patience

Karen

**Comment by yippeeeyay** [comment]
Afaik it was fixed on nvidia with a driver update from their side. Also from Intels side, on driver 101.6083_101.5736 this issue is not present at all, so that leaves me confused.

**Comment by yippeeeyay** [comment]
Sorry, I meant that this issue was not present on driver 101.6083_101.5736 but was present after that driver. 
You can test by downloading this old driver from the internet archive https://web.archive.org/web/20241015005144/https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
Wouldn't that mean it is a driver regression from Intel rather than an issue from discord/chrome?

I don't mean to bother the team by commenting on this issue repeatedly after its closed but just wanted to understand. Thank you

**Comment by yippeeeyay** [comment]
This bug seems to be fixed from Discord's side after an update changing the GIF picker to prefer WebP over raw GIF and WebM over MP4 for better performance (source: https://x.com/advaithj1/status/1947485639366349119)

**Comment by Squall-Leonhart** [comment]
This has been fixed on windows end.
   
>  * [Display and Graphics] Fixed an issue where apps and browsers could have partially stuck onscreen content when other maximized / full screen apps were updating in the background. This may have been noticeable particularly when trying to scroll the window content, as only some parts would update.

**Comment by Karen-Intel** [comment]
Closing as fixed on Windows latest update

**Comment by Wallby** [comment]
I am on the latest driver version (32.0.101.8331) and this issue started re-occurring. It seemed fixed initially. I checked and the driver wasn't rolled back. At least the partially stuck on-screen content still happens in games, as well as black flashes.
