### ISSUE TITLE
BSOD & Device remove ect in Pioneers of Pagonia

### ISSUE THREAD

**Issue by RalfKornmannEnvision** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#1127]
### Requirements

- [x] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates)
- [x] Game is not cracked, modded and use the latest patch

### Game

Pioneers of Pagonia 

### Game acquisition link

https://store.steampowered.com/app/2155180/Pioneers_of_Pagonia

### Game Platform

Steam

### Processor / Processor Number

Ryzen 9 3950X 16 Core processor

### Graphic Card

Arc A310 

### GPU Driver Version

32.0.101.6874

### Rendering API

DirectX 12

### Windows Build

Windows 10 22H2

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/user-attachments/files/20563199/igcit_ssu.txt)

### Description and steps to reproduce

Freezes, device removes, BSOD, etc when starting the public alpha version before it enters the main menu.

the alpha version introduces some new shader. I was able to track it down to a somewhat complicated pixel shader. Unfortunately I was not able to identify the part of the shader that is causing the issue as even small changes could trigger it or not.

Other players with Arc A and B series hardware have reported this issue to us, too.

### Game graphic quality *

- [x] Low
- [x] Medium
- [x] High
- [x] Ultra

### Game resolution

1920*1080 but happens with any resolution

### Game VSync

On

### Game display mode

Borderless Windowed

### Detailed game settings

default settings as it happens before the main menu shows up

### Device / Platform name

ASROCK A310 LP 4G

**Comment by RalfKornmannEnvision** [comment]
Feel free to contact us if you need more informations or special builds of the game

**Comment by Gabriela-Intel** [comment]
Thanks for your report! I'll look into this and get back to you soon.

**Comment by Gabriela-Intel** [comment]
Hey there.

I've tried reproducing the issue various times using different HW and our latest driver ([101.6881](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html)), but I haven't seen any issues when loading into the main menu. I see in the bug report you mentioned Windows 10. 

Is the issue only occurring in Win10, or is it also when using Win11?
Additionally, is this an occasional issue, or does it occur 100% of the time?

I tried reproducing on the following systems:
- i5-14600k + B580
- i5-14600k + A750
- AMD Ryzen 5 7600 + B580
- AMD Ryzen 5 7600 + A770

**Comment by RalfKornmannEnvision** [comment]
Thank you for looking into this

Please make sure you select "Alpha" in the steam game properties beta section (Beta Participation). The regular (none) and the beta version are still working fine. The problematic shader is new but unfortunately essential.

The crash happens always for me. Just the outcome varies from a device remove up to a BSOD 

101.6881 was not available at the time I created this ticket. I will retest with it as soon as possible but I expect it will not happen before monday next week.

**Comment by Gabriela-Intel** [comment]
That's what I was missing, thanks so much! I see the issue now.

I captured some logs and escalated the issue by submitting an official bug report internally. I don't have an ETA at the time, but I will post here once I have something to share on the status of the issue 

Thanks again for reporting this :)

**Comment by RalfKornmannEnvision** [comment]
Glad you were able to reproduce it.

If there is something else we can do to support you and your team with this please don't hesitate to ask.

**Comment by Gabriela-Intel** [comment]
Hello, our developments folks have asked to pass this along. Is there any way you can help with this? 

**Are they familiar with Intel Breadcrumbs? Or any different way to identify culprit PS (here it is used with GS). Then, they could either recheck if they calculate the addresses correctly, or share the shader with us.**

Since this game is in early release, it might be tough to get this prioritized so any extra information would be good to help maybe get this moving along.

**Comment by RalfKornmannEnvision** [comment]
Actually I am not. Is there any documentation available how to integrate or use it? If I know the necessary steps I can do it.

In the meantime I will see if I can pinpoint down the exact permutation of the shader that causes the issue. 

I am not sure if this information helps but we have some player reports that disabling the resizable BAR prevents the crash and make it playable again.

**Comment by RalfKornmannEnvision** [comment]
It is somehow related to this pixel shader. All Variants including the one without any of the optional code parts that are activated with the preprocessor defines. Just outputting some default values to all 3 or 4 targets prevents the crash but does of course break the rendering. 

I tried to reduce it more to find the problematic area in the code but had no luck.

As the BAR is somehow involved in this I suspect that the issue is not the shader itself but the mapping of the resources it uses. All the const buffers it uses are part of one or more larger buffer that are created in the system memory. Each one is set with a seperate call to SetGraphicsRootConstantBufferView. There is some indirect indexing going on. That's just guesswork but it might be possible that the driver does not make enough of this large buffer actually accessible from the GPU or some data still stuck in a cache that the GPU cannot see.

I was not able to find documentation about  Intel Breadcrumbs. We have implemented the regular DX12 DRED system if this helps.
```
static const bool c_clampTangents = false;

float4 PrepareSpline(float4 p, bool clampTangents = true)
{
    const float d = p.z - p.y;
    const float absD = abs(d);
    const float clampFactor = 3 * absD;

    float2 m = 0.5 * (p.zw - p.xy);
    if (clampTangents || c_clampTangents)
    {
        // Fritsch-Carlson method
        m = absD < 1e-5 ? 0 : select(m * d < 0, 0, m);
        m = select(abs(m) > clampFactor, clampFactor * sign(m), m);
    }

    // Hermite polynomial coefficients
    return float4(
        2.0 * p.y - 2.0 * p.z + m.x + m.y,
        -3.0 * p.y + 3.0 * p.z - 2.0 * m.x - m.y,
        m.x,
        p.y);
}

float3 CalculateTerrainShape(float2 uv, const float4 heights[4], out float3 tangent, out float3 bitangent, out float3 normal)
{
    const float4 u = float4(uv.x * uv.x * uv.x, uv.x * uv.x, uv.x, 1);
    const float4 v = float4(uv.y * uv.y * uv.y, uv.y * uv.y, uv.y, 1);
    const float3 d = float3(3, 2, 1);
    const float3 du = u.yzw * d;
    const float3 dv = v.yzw * d;
    const float4 uHeights = float4(
        dot(PrepareSpline(heights[0]), u),
        dot(PrepareSpline(heights[1]), u),
        dot(PrepareSpline(heights[2]), u),
        dot(PrepareSpline(heights[3]), u)
    );
    const float4 duHeights = float4(
        dot(PrepareSpline(heights[0], false).xyz, du),
        dot(PrepareSpline(heights[1], false).xyz, du),
        dot(PrepareSpline(heights[2], false).xyz, du),
        0
    );

    tangent = -normalize(float3(0, dot(PrepareSpline(uHeights, false).xyz, dv), 1));
    bitangent = normalize(float3(1, dot(PrepareSpline(duHeights, false), v), 0));
    normal = normalize(cross(bitangent, tangent));

    return float3(uv.x, dot(PrepareSpline(uHeights), v), uv.y);
}

float3 CalculateTerrainShape(float2 uv, const float4 heights[4])
{
    const float4 u = float4(uv.x * uv.x * uv.x, uv.x * uv.x, uv.x, 1);
    const float4 v = float4(uv.y * uv.y * uv.y, uv.y * uv.y, uv.y, 1);
    const float4 uHeights = float4(
        dot(PrepareSpline(heights[0]), u),
        dot(PrepareSpline(heights[1]), u),
        dot(PrepareSpline(heights[2]), u),
        dot(PrepareSpline(heights[3]), u)
    );

    return float3(uv.x, dot(PrepareSpline(uHeights), v), uv.y);
}
//#define HASDECALS 1
//#define HASEMISSIVEDECALS 1

struct GS_OUTPUT
{
    float4 Position : SV_POSITION;
    uint TileIndex : INDEX;
    float2 UV : UV;
};

struct PS_OUTPUT
{
    float4 Color : SV_TARGET0;
    float4 Normal : SV_TARGET1;
    float4 Parameter : SV_TARGET2;
#if HASDECALS && HASEMISSIVEDECALS    
    float4 Emissive : SV_TARGET3;
#endif    
};

struct STileData
{
    float2 WorldPosition;
    uint SedimentOffset;
    uint SedimentCount;
    float4 Heights[4];
};

struct SSedimentData
{
    uint Type;
    uint Blend;
};


struct SSedimentTextureData
{
    uint TopColorId;
    uint TopNormalId;
    uint TopParameterId;
    float TopScale;
    
    uint SideColorId;
    uint SideNormalId;
    uint SideParameterId;
    float SideScale;
    
    uint RoadColorId;
    uint RoadNormalId;
    uint RoadParameterId;
    float RoadScale;

    float TopHeightScale;
    float SideHeightScale;
    float RoadHeightScale;
    float _padding;
};

struct SDecalData
{
    float3 CoordsU;
    float Blend;
    float3 CoordsV;
    float HeightOffset;
    float2 RotationU;
    float2 RotationV;
    uint ColorId;
    uint NormalId;
    uint ParameterId;
    uint EmissiveId;
    float4 EmissiveData;
};

cbuffer TileData
{
    STileData g_TileData[18 * 18];
};

cbuffer SedimentTextureData
{
    SSedimentTextureData g_SedimentTextureData[256];
};

cbuffer SedimentData
{
    SSedimentData g_SedimentData[4096];
};

SamplerState SedimentSampler : register(s0, space1000);

#if HASROADS
Texture2D tRoadMask;
#endif

#if HASDECALS
cbuffer DecalData
{
    SDecalData g_DecalData[819];
};

uint decalCount;
#endif

Texture2D tAllTextures[];

struct TriBlendData
{
    float2 texCoordsX;
    float2 texCoordsY;
    float2 texCoordsZ;
    float3 blend;
    float nrmFlipX;
    float nrmFlipZ;
};

float3 GetTriplanarSigns(float3 normal)
{
    normal.x = -normal.x;
    return step(0, normal) * 2 - 1;
}

static const float TriplanarBlendOffset = 0.4;
static const float TriplanarBlendExponent = 16;
static const float TriplanarBlendHeightStrength = 0.6;
static const float TriplanarBlendYScale = 0.9;

static const float RoadHeightBlendSoftness = 0.3;
static const float DecalHeightBlendSoftness = 0.1;
static const float HeightBlendSoftness = 0.5;

float3 GetTriplanarBlend(float3 normal)
{
    normal = normalize(normal * float3(1, TriplanarBlendYScale, 1));
    float3 blend = saturate(abs(normal) - TriplanarBlendOffset);
    blend = pow(blend, TriplanarBlendExponent);
    return blend / (blend.x + blend.y + blend.z);
}

TriBlendData GetTriBlendData(float3 pos, float3 normal)
{
    TriBlendData data;
    
    data.blend = GetTriplanarBlend(normal);
    
    float3 s = GetTriplanarSigns(normal);

    data.texCoordsX = -pos.zy;
    data.texCoordsX.x *= s.x;
    data.nrmFlipX = s.x;
    
    data.texCoordsY = pos.zx;
    data.texCoordsY.x *= s.y;
    
    data.texCoordsZ = -pos.xy;
    data.texCoordsZ.x *= s.z;
    data.nrmFlipZ = s.z;
    
    return data;
}

float2 GetHeightBlend2(float2 heights, float softness)
{
    float height_start = max(heights.x, heights.y) - softness;
    float2 b = max(heights - height_start, 0);
    float sum = b.x + b.y;
    return sum == 0 ? 0 : b / sum;
}

struct SedimentSample
{
    float3 Color;
    float3 Normal;
    float4 Parameter;
};

float GetSedimentHeight(uint id, in TriBlendData tribd, float road)
{
    float height = 0;
    
    SSedimentTextureData sediment = g_SedimentTextureData[id];
    
    if (road < 1)
    {
        tribd.blend *= float3(sediment.SideHeightScale, sediment.TopHeightScale, sediment.SideHeightScale) * TriplanarBlendHeightStrength;
        tribd.blend /= (tribd.blend.x + tribd.blend.y + tribd.blend.z);
        if (tribd.blend.y > 0)
        {
            height += tAllTextures[NonUniformResourceIndex(sediment.TopParameterId)].Sample(SedimentSampler, tribd.texCoordsY * sediment.TopScale).w * tribd.blend.y * sediment.TopHeightScale;
        }
    
        if (tribd.blend.x > 0)
        {
            height += tAllTextures[NonUniformResourceIndex(sediment.SideParameterId)].Sample(SedimentSampler, tribd.texCoordsX * sediment.SideScale).w * tribd.blend.x * sediment.SideHeightScale;
        }
    
        if (tribd.blend.z > 0)
        {
            height += tAllTextures[NonUniformResourceIndex(sediment.SideParameterId)].Sample(SedimentSampler, tribd.texCoordsZ * sediment.SideScale).w * tribd.blend.z * sediment.SideHeightScale;
        }
    }
    
    if (road > 0)
    {
        float2 texcoords = tribd.texCoordsY * sediment.RoadScale;
        float4 roadParameter = tAllTextures[NonUniformResourceIndex(sediment.RoadParameterId)].Sample(SedimentSampler, texcoords);
        roadParameter.w *= sediment.RoadHeightScale * sediment.TopHeightScale;
        float roadBlend;

        if (road < 1)
        {
            float2 blend = GetHeightBlend2(1 + float2(roadParameter.w * road, height * (1 - road)), RoadHeightBlendSoftness);
            roadBlend = blend.x;
            height *= blend.y;
        }
        else
        {
            roadBlend = 1;
        }

        if (roadBlend > 0)
        {
            height += roadParameter.w * roadBlend;
        }
    }
    
    return height;
}

SedimentSample GetSedimentSample(uint id, in TriBlendData tribd, float road)
{
    SedimentSample result;
    
    result.Color = float3(0, 0, 0);
    result.Normal = float3(0, 0, 0);
    result.Parameter = float4(0, 0, 0, 0);
    
    SSedimentTextureData sediment = g_SedimentTextureData[id];

    if (road < 1)
    {
        tribd.blend *= float3(sediment.SideHeightScale, sediment.TopHeightScale, sediment.SideHeightScale) * TriplanarBlendHeightStrength;
        tribd.blend /= (tribd.blend.x + tribd.blend.y + tribd.blend.z);
        if (tribd.blend.y > 0)
        {
            float4 topScale = float4(1, 1, 1, sediment.TopHeightScale);
            float2 texcoords = tribd.texCoordsY * sediment.TopScale;
            result.Color.xyz += tAllTextures[NonUniformResourceIndex(sediment.TopColorId)].Sample(SedimentSampler, texcoords).xyz * tribd.blend.y;
            float3 nrm = tAllTextures[NonUniformResourceIndex(sediment.TopNormalId)].Sample(SedimentSampler, texcoords).xyz * 2 - 1;
            nrm.x *= -1;
            result.Normal.xyz += nrm * tribd.blend.y;
            result.Parameter += tAllTextures[NonUniformResourceIndex(sediment.TopParameterId)].Sample(SedimentSampler, texcoords) * tribd.blend.y * topScale;
        }
    
        if (tribd.blend.x > 0)
        {
            float4 sideScale = float4(1, 1, 1, sediment.SideHeightScale);
            float2 texcoords = tribd.texCoordsX * sediment.SideScale;
            result.Color.xyz += tAllTextures[NonUniformResourceIndex(sediment.SideColorId)].Sample(SedimentSampler, texcoords).xyz * tribd.blend.x;
            float3 nrm = tAllTextures[NonUniformResourceIndex(sediment.SideNormalId)].Sample(SedimentSampler, texcoords).xyz * 2 - 1;
            nrm.x *= tribd.nrmFlipX;
            nrm.y *= -tribd.nrmFlipX;
            result.Normal.xyz += nrm * tribd.blend.x;
            result.Parameter += tAllTextures[NonUniformResourceIndex(sediment.SideParameterId)].Sample(SedimentSampler, texcoords) * tribd.blend.x * sideScale;
        }
    
        if (tribd.blend.z > 0)
        {
            float4 sideScale = float4(1, 1, 1, sediment.SideHeightScale);
            float2 texcoords = tribd.texCoordsZ * sediment.SideScale;
            result.Color.xyz += tAllTextures[NonUniformResourceIndex(sediment.SideColorId)].Sample(SedimentSampler, texcoords).xyz * tribd.blend.z;
            float3 nrm = tAllTextures[NonUniformResourceIndex(sediment.SideNormalId)].Sample(SedimentSampler, texcoords).xyz * 2 - 1;
            nrm.xy = nrm.yx * tribd.nrmFlipZ;
            result.Normal.xyz += nrm * tribd.blend.z;
            result.Parameter += tAllTextures[NonUniformResourceIndex(sediment.SideParameterId)].Sample(SedimentSampler, texcoords) * tribd.blend.z * sideScale;
        }
    }
    
    if (road > 0)
    {
        float2 texcoords = tribd.texCoordsY * sediment.RoadScale;
        float4 roadParameter = tAllTextures[NonUniformResourceIndex(sediment.RoadParameterId)].Sample(SedimentSampler, texcoords);
        roadParameter.w *= sediment.RoadHeightScale * sediment.TopHeightScale;
        
        float roadBlend;
        
        if (road < 1)
        {
            float2 blend = GetHeightBlend2(1 + float2(roadParameter.w * road, result.Parameter.w * (1 - road)), RoadHeightBlendSoftness);
            
            roadBlend = blend.x;
            
            result.Color *= blend.y;
            result.Normal *= blend.y;
            result.Parameter *= blend.y;
        }
        else
        {
            roadBlend = 1;
        }
        
        if (roadBlend > 0)
        {
            result.Color.xyz += tAllTextures[NonUniformResourceIndex(sediment.RoadColorId)].Sample(SedimentSampler, texcoords).xyz * roadBlend;
            float3 nrm = tAllTextures[NonUniformResourceIndex(sediment.RoadNormalId)].Sample(SedimentSampler, texcoords).xyz * 2 - 1;
            nrm.x *= -1;
            result.Normal.xyz += nrm * roadBlend;
            result.Parameter += roadParameter * roadBlend;
        }
    }
    
    return result;
}

float4 UINT4_UNORM_to_FLOAT4(uint packedInput)
{
    float4 unpackedOutput;
    unpackedOutput.x = (float) (packedInput & 0x000000ff) / 255;
    unpackedOutput.y = (float) (((packedInput >> 8) & 0x000000ff)) / 255;
    unpackedOutput.z = (float) (((packedInput >> 16) & 0x000000ff)) / 255;
    unpackedOutput.w = (float) (packedInput >> 24) / 255;
    return unpackedOutput;
}

SedimentSample BlendSediments(uint count, uint offset, in TriBlendData tribd, float2 uv, float road)
{
    // TAM can we optimize this?
    float4 mixblend1 = lerp(float4(1, 0, 0, 0), float4(0, 1, 0, 0), uv.x);
    float4 mixblend2 = lerp(float4(0, 0, 1, 0), float4(0, 0, 0, 1), uv.x);
    float4 mixblendMask = lerp(mixblend1, mixblend2, uv.y);
    
    uint sOffset = offset;
    
    float maxHeight = 0;
    
    for (uint i = 0; i < count; i++)
    {
        float blend = dot(mixblendMask, UINT4_UNORM_to_FLOAT4(g_SedimentData[sOffset].Blend));
        
        uint sedimentId = g_SedimentData[sOffset].Type;
    
        maxHeight = max(maxHeight, (1 + GetSedimentHeight(sedimentId, tribd, road)) * blend);
        
        sOffset++;
    }
    
    maxHeight -= HeightBlendSoftness;
    
    SedimentSample result;
    
    result.Color = float3(0, 0, 0);
    result.Normal = float3(0, 0, 0);
    result.Parameter = float4(0, 0, 0, 0);
    
    float blendSum = 0;
    
    sOffset = offset;
    
    for (uint i = 0; i < count; i++)
    {
        float blend = dot(mixblendMask, UINT4_UNORM_to_FLOAT4(g_SedimentData[sOffset].Blend));
        
        uint sedimentId = g_SedimentData[sOffset].Type;
        
        float layerBlend = max(0, ((1 + GetSedimentHeight(sedimentId, tribd, road)) * blend) - maxHeight);
        
        if (layerBlend > 0)
        {
            SedimentSample layer = GetSedimentSample(sedimentId, tribd, road);
       
            result.Color += layer.Color * layerBlend;
            result.Normal += layer.Normal * layerBlend;
            result.Parameter += layer.Parameter * layerBlend;
        
            blendSum += layerBlend;
        }
        
        sOffset++;
    }
    
    float blendFactor = 1 / blendSum;
    
    result.Color *= blendFactor;
    result.Normal *= blendFactor;
    result.Parameter *= blendFactor;
    
    return result;
}

PS_OUTPUT ps_main(GS_OUTPUT input)
{
    STileData tileData = g_TileData[input.TileIndex];
    
    float3 tangent;
    float3 bitangent;
    float3 normal;
    
    float3 pos = CalculateTerrainShape(input.UV, tileData.Heights, tangent, bitangent, normal);
    float3 worldPos = float3(tileData.WorldPosition.x, 0, tileData.WorldPosition.y) + pos;
    TriBlendData tribd = GetTriBlendData(worldPos, normal);

#if HASROADS    
    float road = tRoadMask.Load(int3(input.Position.xy, 0)).x;
#else
    float road = 0;
#endif    
    
    PS_OUTPUT output;
   
    float3 normalOut;
    
    switch (tileData.SedimentCount)
    {
        case 1:
            {
                uint sedimentId = g_SedimentData[tileData.SedimentOffset].Type;
    
                SedimentSample sample = GetSedimentSample(sedimentId, tribd, road);
   
                output.Color = float4(sample.Color, 1);
                normalOut = sample.Normal;
                output.Parameter = float4(sample.Parameter.xyz, 0);
            }
            break;
        
        // TODO optimize for common multi layer modes
        
        default:
            SedimentSample sample = BlendSediments(tileData.SedimentCount, tileData.SedimentOffset, tribd, input.UV, road);
   
            output.Color = float4(sample.Color, 1);
            normalOut = sample.Normal;
            output.Parameter = float4(sample.Parameter.xyz, 0);
            break;
    }
    
#if HASDECALS
    int activeDecals = 0;
    int activeId = 0;
    float4 activeDecalColor;
    float2 activeUV;
    
    float3 decalpos = float3(worldPos.x, worldPos.z, 1);
    
    for (uint i = 0; i < decalCount; i++)
    {
        float2 uv = float2(dot(decalpos, g_DecalData[i].CoordsU), dot(decalpos, g_DecalData[i].CoordsV));
                
        if (all(uv == saturate(uv)))
        {
            float4 color = tAllTextures[NonUniformResourceIndex(g_DecalData[i].ColorId)].Sample(SedimentSampler, uv);
    
            if ((color.w * g_DecalData[i].Blend)  != 0.0)
            {
                activeDecals++;
                
                if (activeDecals > 1)
                {
                    break;
                }
                
                activeId = i;
                activeUV = uv;
                activeDecalColor = color;
            }
        }
    }
    
    if (activeDecals > 0)
    {
        float decalBlend;
        float groundBlend;
        
        float3 decalNormal;
        float4 decalParameter;
    
#if HASEMISSIVEDECALS
        float3 decalEmissive = float3(0, 0, 0);
#endif
       
        if (activeDecals == 1)
        {
            decalParameter = tAllTextures[NonUniformResourceIndex(g_DecalData[activeId].ParameterId)].Sample(SedimentSampler, activeUV);
            decalNormal = tAllTextures[NonUniformResourceIndex(g_DecalData[activeId].NormalId)].Sample(SedimentSampler, activeUV).xyz * 2 - 1;
            decalNormal.x *= -1;
            
            decalNormal.xy = float2
            (
                dot(g_DecalData[activeId].RotationU, decalNormal.xy),
                dot(g_DecalData[activeId].RotationV, decalNormal.xy)
            );
           
#if HASEMISSIVEDECALS            
            float4 emissiveData = g_DecalData[activeId].EmissiveData;
            float3 emissive = emissiveData.xyz;
    
            int eId = g_DecalData[activeId].EmissiveId;
    
            if (eId != 0)
            {
                emissive += tAllTextures[NonUniformResourceIndex(eId)].Sample(SedimentSampler, activeUV).xyz;
            }
    
            decalEmissive += emissive * emissiveData.w;
#endif            
        }
        else
        {
            float maxHeight = 0;
            
            uint lastId = activeId;
    
            for (uint i = activeId; i < decalCount; i++)
            {
                float2 uv = float2(dot(decalpos, g_DecalData[i].CoordsU), dot(decalpos, g_DecalData[i].CoordsV));
                
                if (all(uv == saturate(uv)))
                {
                    float alpha = tAllTextures[NonUniformResourceIndex(g_DecalData[i].ColorId)].Sample(SedimentSampler, uv).w * g_DecalData[i].Blend;
                    float height = tAllTextures[NonUniformResourceIndex(g_DecalData[i].ParameterId)].Sample(SedimentSampler, uv).w + g_DecalData[i].HeightOffset;
    
                    maxHeight = max(maxHeight, height * alpha);
                    
                    lastId = i;
                }
            }
            
            float minHeight = max (0, maxHeight - HeightBlendSoftness);
            
            activeDecalColor = float4(0, 0, 0, 0);
            decalNormal = float3(0, 0, 0);
            decalParameter = float4(0, 0, 0, 0);
   
            float blendSum = 0;
    
            for (uint i = activeId; i <= lastId; i++)
            {
                float2 uv = float2(dot(decalpos, g_DecalData[i].CoordsU), dot(decalpos, g_DecalData[i].CoordsV));
                
                if (all(uv == saturate(uv)))
                {
                    float4 dColor = tAllTextures[NonUniformResourceIndex(g_DecalData[i].ColorId)].Sample(SedimentSampler, uv);
                    dColor.w *= g_DecalData[i].Blend;
                    
                    float4 dParameter = tAllTextures[NonUniformResourceIndex(g_DecalData[i].ParameterId)].Sample(SedimentSampler, uv);
                    dParameter.w += g_DecalData[i].HeightOffset;
       
                    float height = dParameter.w * dColor.w;
                    float layerBlend = max (0, height - minHeight);

                    if (layerBlend > 0)
                    {
                        float3 dNormal = tAllTextures[NonUniformResourceIndex(g_DecalData[i].NormalId)].Sample(SedimentSampler, uv).xyz * 2 - 1;
                        dNormal.x *= -1;
                        
                        dNormal.xy = float2
                        (
                            dot(g_DecalData[i].RotationU, dNormal.xy),
                            dot(g_DecalData[i].RotationV, dNormal.xy)
                        );
                        
                        activeDecalColor += dColor * layerBlend;
                        decalNormal += dNormal * layerBlend;
                        decalParameter += dParameter * layerBlend;
                    
#if HASEMISSIVEDECALS      
                        float4 emissiveData = g_DecalData[i].EmissiveData;
                        float3 emissive = emissiveData.xyz;
                    
                        int eId = g_DecalData[i].EmissiveId;
            
                        if (eId != 0)
                        {
                            emissive += tAllTextures[NonUniformResourceIndex(eId)].Sample(SedimentSampler, uv).xyz;
                        }
                    
                        decalEmissive += emissive * emissiveData.w * layerBlend;
#endif                    
                        blendSum += layerBlend;
                    }
                }
            }
    
            float blendFactor =  blendSum < 0.001 ? 0 : 1 / blendSum;
    
            activeDecalColor *= blendFactor;
            decalNormal *= blendFactor;
            decalParameter *= blendFactor;
    
#if HASEMISSIVEDECALS
            decalEmissive *= blendFactor;
#endif 
        }
        
        float2 blend = activeDecalColor.w > 0.001 ? GetHeightBlend2(1 + float2(decalParameter.w * activeDecalColor.w, output.Parameter.w * (1 - activeDecalColor.w)), DecalHeightBlendSoftness) : float2 (0, 1);
            
        decalBlend = blend.x;
        groundBlend = blend.y;
        
        output.Color.xyz *= groundBlend;
        normalOut *= groundBlend;
        output.Parameter *= groundBlend;
        
        output.Color.xyz += activeDecalColor.xyz * decalBlend;
        normalOut += decalNormal * decalBlend;
        output.Parameter += decalParameter * decalBlend;
        
#if HASEMISSIVEDECALS
        output.Emissive.xyz = decalEmissive * decalBlend;
        output.Emissive.w = 0;
#endif
    }    
#if HASEMISSIVEDECALS
    else
    {
        output.Emissive = float4 (0, 0, 0, 0);
    }
#endif        
    
#endif    
    
    float3x3 tbn = float3x3(tangent, -bitangent, normal);
    output.Normal = float4((mul(normalize(normalOut), tbn) + 1.0) * 0.5, 0.0);

    return output;
}

```

**Comment by Gabriela-Intel** [comment]
Thank you so much for all this extra information! This really helps. I've passed along your latest comment.  Let me get back to you on this.

**Comment by Gabriela-Intel** [comment]
Hello and thank you so much for your patience.

I don't see the "alpha" option anymore in the Steam game properties. However, this issue reported here should be resolved with the latest driver [101.8132](https://www.intel.com/content/www/us/en/download/785597/intel-arc-graphics-windows.html).

**Comment by RalfKornmannEnvision** [comment]
'Alpha' has been rolled over into Beta a while ago. And 'Beta' is also already in the regular steam version too. Because everything is currently the same we have disabled 'Alpha'. 

I will have a look when I am back in the office (where we have all the GPUs) on Monday. But if you say so I am confident it is fixed.

Thank you for taking care of this issue before we will have our 1.0 release on December 11th.

**Comment by Gabriela-Intel** [comment]
How exciting!

I did test it out myself, and I had no issues at the main menu/before the main menu. If you see otherwise, then please let me know.

Thanks :)

**Comment by Gabriela-Intel** [comment]
Hello. Checking if you had the chance to test this out?

**Comment by RalfKornmannEnvision** [comment]
Sorry for the late response. We had a public holiday over here.

Unfortunately it still causes a device remove (page fault) with the A310 and the latest drivers for me. 

The feedback from our players is mixed. Some reported it's now fixed for them while others still have the issue. At least one player claimed that it actually worked before but after the driver update not anymore.

As an additional information: It starts kind to work for me if I enable the DirectX debug layer with a validation shader path mode. Either guarded or unguarded work. But no errors are reported by the debug layer. As it runs very slow it easily triggers an device remove because of a timeout.

**Comment by Gabriela-Intel** [comment]
Huh, I tried it again and I'm seeing the error message now. False alarm, my apologies. Thanks for checking anyways.

**Comment by RalfKornmannEnvision** [comment]
I did some more checks. It looks like that the newest driver fixes the problem at least partial. The shader has multiple permutations. The base shader and the base shader + roads (#define HASROADS 1) seems to work now. The permutations that include decals (#define HASDECALS 1) still cause a device remove. As the driver now reacts less erratic to changes in the shader code I might be able to narrow it down some more.

**Comment by Gabriela-Intel** [comment]
Hey there. Thanks so much for your patience! This is resolved with driver [101.8509](https://www.intel.com/content/www/us/en/download/785597/intel-arc-graphics-windows.html). I tested it myself to confirm :)

**Comment by Gabriela-Intel** [comment]
Please let me know if you see the same results on your end.

**Comment by Gabriela-Intel** [comment]
Hello! Wondering if you have any updates?

**Comment by Gabriela-Intel** [comment]
Since there are no updates on the status, I'll proceed with closure. Let us know if you get the chance to check this out.
