### ISSUE TITLE
Yakuza Kiwami 2 - Framerate/Perfomance issues

### ISSUE THREAD

**Issue by adancingmilk** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#163]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Yakuza Kiwami 2

### Game Platform [Required]

- [X] Steam
- [ ] Origin
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-11400

### Graphic Card [Required]

Intel ARC A770 LE 16GB

### GPU Driver Version [Required]

- [ ] 31.0.101.3491 (*latest*)
- [X] 31.0.101.3490
- [ ] 31.0.101.3430
- [ ] 31.0.101.3276
- [ ] 30.0.101.3268
- [ ] 30.0.101.3259
- [ ] 30.0.101.1743

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [X] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H1 (*October 2021 Update*)
- [ ] Windows 10 21H2 (*November 2021 Update*)
- [ ] Windows 10 21H1 (*May 2021 Update*)
- [ ] Windows 10 20H2 (*October 2020 Update*)
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/9858779/igcit_ssu.txt)

### Description and steps to reproduce [Required]

- Description
The game can't manage to run at a stable 60FPS. It's constantly between 37~60FPS depending on how many NPC are in the streets. It can't be a graphics-too-high issue since the game has the same performance when all settings are set on Low. GPU power consumption is around 70-80W with the game settings provided below, and goes straight above 100-150W when setting anti-aliasing to SMAA x1.25 or more.

- Steps to reproduce
Launching the game from Steam as usual with Driver 31.0.101.3490.

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

- Settings
Output Device : Display 1
Display Mode : Fullscreen
Resolution : 1920x1080
Refresh Rate : 60.00Hz
Vertical Sync : On
Quality : Custom
FOV : 40
FPS : Unlimited

- Advanced Settings
Texture Quality : High
Texture Filtering : 16x
Shadows Quality : High
Geometry Quality : High
Realtime Reflections : On
Motion Blur : On
SSAO : On
Render-Scale : 100%
Anti-aliasing : SMAA
Depth Of Field : On

### Crash dumps [Required]

None (performance issue but no crashs)

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,

For further investigation  we would like to know below information from your side:

- Make and model the display used to see the issue?
- Single display,clone,or extended ?
- AC or DC mode,i.e. is the power cable plugged in or not?
- Since you didn't mention the device or platform used in the details, please provide
- We would appreciate it if you could provide a screen shot or short video of the issue in order to better understand. As we are verifying the issue on our side, it will be helpful for us to make sure we are all on the same page.

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,
Could you answer the above questions asked?

**Comment by adancingmilk** [comment]
Hi ! Here are the information asked : 
- Display used : iiyama G-Master GE2788HS
- Single Display
- Power cable always plugged, I'm using a PC
- As for the screenshot, I recorded FPS during 350 seconds. Here is the graph : 
![image](https://user-images.githubusercontent.com/61962757/198971743-20b2550d-2924-43f4-9068-c81212760ed6.png)

At first, I ran around the map ("Kamurocho"), FPS were very unstable. It then stabilized at 60 after 80 seconds because there was a cutscene, before going down again after the cutscene finished. The performance is the same whatever the setting used, I'm going to edit the issue to mention it.

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,
Could you give a try with the BETA driver version [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html) and see issue is still seeing. Please give a try with the driver given and let me know the observation

**Comment by adancingmilk** [comment]
I just tried the BETA Driver 31.1.101.3793 (with clean install and everything) and I get the same performance as the stable driver.

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,

Thank you for the result and confirmation on the latest driver.
I will verify the issue on our side and let you know the updates. Please stay tuned.

**Comment by IntelSupport-Arun** [comment]
Hi @adancingmilk ,
Sorry for the delay.
I have verified the issue on our side and am able  to reproduce the issue on our latest graphics drivers  31.0.101.3490 and [31.0.101.3793](https://www.intel.com/content/www/us/en/download/729157/751349/intel-arc-graphics-windows-dch-driver-beta.html). Here is the observation from our side :
![Gfx_BETA_3793](https://user-images.githubusercontent.com/91881865/200771702-590c7668-c4fa-45a3-b318-247807fd24fa.JPG)
Same time I can see similar behavior or internal driver as well. Based on my result I have escalated this issue to the next level for further support for the fix.
Same time  I want to give you a heads-up that the fix may take 3 to 6 months to be included. 
So please stay tuned for the next update from us. Thank you for your patience.

**Comment by EliezYT** [comment]
There has been many updates to the drivers for the DirectX11 Api which is what the game runs on. Are you still experiencing these issues because I'm not?

**Comment by anto-lcd** [comment]
I can confirm that I'm still experiencing these issues, even with the latest driver 4676. Whatever the graphics settings used in 1080p, the game runs between 25 and 60 FPS depending the area and GPU usage varies between 40 and 60% (Percentage based on performance with max settings at 1080p). Lowering the resolution doesn't fix anything regarding the performance.

**Comment by anto-lcd** [comment]
Still the same with driver 4887.

**Comment by BiZkViT96** [comment]
"3 to 6 months" turned into 12+ months. @Karen-Intel @Arturo-Intel I understand that this is not your issue (i have no idea if @IntelSupport-Arun still work at Intel) and im sorry for tagging you, but how this is possible? I think we can all agree that this is unacceptable.

If issue was replicated and not fixed in 12 months it should get highest priority. The same with "regressions", how any company can develop software if development continues on top of regressions and fix MAY take up to 6 months is beyond my understanding.

And can we have a little talk about "Won't fix"? @anto-lcd this is a trajectory of this issue.

Intel is company with 149.837B market cap, and users getting cooked for many months just to find that issue won't be fixed. Why? - "development team limited resources and needing to work on other higher priority game issues". Im mean, just look at this! https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/74 https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/162 https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/issues/115

"Won't fix" category should be reserved for cases when problem is on the game side and it up to game devs fix that issue. It should not be used as we don't have a time excuse. Regressions and 12+ months replicated issues should be top priority.

All closed and replicated "Won't fix" issues should be retested and reopened if previously it was found that issue it on driver side. It should not being used to make bug list shorter.

Arturo, Karen, i understand that you small people, but I will appreciate if you push what been said above to the people who can make any changes. Thank you!

**Comment by mbtns** [comment]
I realize I am a bit late with this reply, but only figured this out myself recently. 
I can confirm this issue still persists with Yakuza Kiwami as well on Win10 with A770 LE.

What fixed this - for me - was installing [DXVK](https://github.com/doitsujin/dxvk) for the game, you can follow [this Steam Community tutorial](https://steamcommunity.com/sharedfiles/filedetails/?id=2576364772) or [the more general one from PCGamingWiki](https://www.pcgamingwiki.com/wiki/DXVK). One quirk I came across is that after launching the game from Steam, I need to L-click my mouse for it the intro movie to start and the game to actually start (otherwise I am stuck in a black screen). After that the game went from trying to keep 30 fps without DXVK to a solid 60 fps on Ultra settings on 1440p. 

Extra tip: If you want some additional info about performance, you can create a file named "dxvk.conf" containing either "DXVK_HUD=1" for some fps and driver info, or better "DXVK_HUD=full" for more info ([source](https://gaming.stackexchange.com/questions/379895/how-do-i-make-sure-that-my-game-is-working-with-vulkan-when-using-dxvk-on-window)).

I found this out when trying to get it to work from within Bottles on Fedora Silverblue (worked very well, but for some reason I could not do manual saves, luckily I dual boot Win10 as well).

Hope this helps people stumbling on this topic in the future trying to play Dragon Engine games.

**Comment by EstebanIntel** [comment]
Hi @anto-lcd,

I have good news: driver [32.0.101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been published and it introduces a fix for the issue with Yakuza Kiwami 2. Please try this driver and if the issue persists let me know. By the way, I know this was reported a long time ago and I do apologize for the time it took to see any progress, so I also want to thank you for your patience and for supporting Intel Arc Graphics.

**Comment by mbtns** [comment]
> Hi @anto-lcd,
> 
> I have good news: driver [32.0.101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been published and it introduces a fix for the issue with Yakuza Kiwami 2. Please try this driver and if the issue persists let me know. By the way, I know this was reported a long time ago and I do apologize for the time it took to see any progress, so I also want to thank you for your patience and for supporting Intel Arc Graphics.

On my system it appears to be performing a lot better now. Thanks.

**Comment by anto-lcd** [comment]
> Hi @anto-lcd,
> 
> I have good news: driver [32.0.101.6127](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) has been published and it introduces a fix for the issue with Yakuza Kiwami 2. Please try this driver and if the issue persists let me know. By the way, I know this was reported a long time ago and I do apologize for the time it took to see any progress, so I also want to thank you for your patience and for supporting Intel Arc Graphics.

Hi ! I confirm that the problem has been fixed on my system. Thank you a lot !!
