### ISSUE TITLE
Artifacting on Judgement (DX12) after launching game from second time onwards

### ISSUE THREAD

**Issue by k-tronix** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#257]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Judgement

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

1165G7/1195G7

### Graphic Card [Required]

Iris Xe

### GPU Driver Version [Required]

- [X] 31.0.101.4146
- [X] 31.0.101.4125
- [ ] 31.0.101.4123
- [X] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793
- [ ] 31.0.101.3491
- [ ] 31.0.101.3490

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [ ] Windows 11 22H2
- [X] Windows 11 21H2
- [X] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Other Windows build number

220000.1574 (Win11;1165G7)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/10862435/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Installed game from Steam. Booted for the first time no issues, no artifacts showing. Quit game and relaunched game and game begins to show artifacts. Replicated the issue on my other 1195G7 device on Win10 22H2 with the same steps. restarting device does not resolve issue. reinstalling driver resolves the issue for the first boot of game after reinstallation but artifacts agsin on second try. Tried 3 drivers version on both device. Screenshot of artifacts attached. 

![screenshot issue](https://user-images.githubusercontent.com/69747766/222181199-cc401228-b094-4e57-8d45-23e218670592.jpg)

### Game graphic quality [Required]

- [X] Low
- [X] Medium
- [ ] High
- [ ] Ultra

### Game resolution [Required]

1280x720

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

in-game low/medium settings

### Device / Platform name

GPD Win3/GPD Winmax2021

### Crash dumps [Required, if applicable]

N/A

### Save game

not save related. Artifacts show on menu screen upon second boot of game.

**Comment by Karen-Intel** [comment]
Hi @k-tronix thank you for your submission

I will proceed to verify the issue on my end and get back to you for any update/help needed

Keep you posted

**Comment by k-tronix** [comment]
Hi Karen-Intel, 

is there any updates on this?

**Comment by Karen-Intel** [comment]
Hey @k-tronix 
Sorry for the delay.
I have been able to confirm the artifacts on Judgement right after you boot the game for the 2nd time in a UHD Graphics 770 12th Gen.
I am reporting this issue internally. 
Just FYI the fix may take from 3 up to 6 months to be included, so please keep your drivers up to date and do not close this post until a fix has been released. And thanks again for helping us reporting it :)

Karen

**Comment by k-tronix** [comment]
Issue still persist on beta driver 4148.

**Comment by k-tronix** [comment]
Issue still persist on March 23rd's driver 4255 stable driver (post for tracking progress)

**Comment by Karen-Intel** [comment]
Hey @k-tronix thank you! Our team is already working on this issue!
I will also post any updates I get on my end :)

Karen

**Comment by Karen-Intel** [comment]
Hey @k-tronix update!
Artifacts are not showing anymore with driver v.4514.[ Could you please verify](https://www.youtube.com/watch?v=8n-yVwIs4hY) so we can close this thread?

Thanks a lot!

Karen

**Comment by Karen-Intel** [comment]
@Arturo-Intel can you please close this one?
Issue has been fixed since driver version 4514, current is 5084

Karen
