### ISSUE TITLE
OBS encoder error while streaming

### ISSUE THREAD

**Issue by zrmdsxa** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#282]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

OBS 29.0.2

### Processor / Processor Number [Required]

Ryzen 7600X

### Graphic Card [Required]

A750 LE

### GPU Driver Version [Required]

- [ ] 31.0.101.4257
- [X] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975
- [ ] 31.0.101.3959
- [ ] 31.0.101.3802
- [ ] 31.0.101.3793

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11174788/report.txt

### Description and steps to reproduce [Required]

This error occurs when streaming World of Warplanes (DX9). Randomly happens while in match. Can happen as fast as 40 seconds after restarting OBS and starting stream. Longest time streamed without problems 1h44m

[qsv encoder: 'advanced_video_stream'] encode failed
Error encoding with encoder 'advanced_video_stream'

![image](https://user-images.githubusercontent.com/5502880/230661635-5e24a775-f1ef-44af-8831-ff8b35f4e0b6.png)

Maps it happened on:
Albion: 1
Alpine Gambit: 1
Asian Border: 1
Cold Peak: 1
Northern Bridgehead: 6
Plateau: 2
Road to Rome: 1

The encoder error is very likely to happen on the map Northern Bridgehead

![image](https://user-images.githubusercontent.com/5502880/230662164-a8b7e350-a34d-49cf-bc6c-b53336c37fe4.png)
![image](https://user-images.githubusercontent.com/5502880/230662202-9bd102b0-6c1a-49f6-b56e-c8ba704f186b.png)
![image](https://user-images.githubusercontent.com/5502880/230662230-874fa74a-1337-4e18-8b52-99c8ab541062.png)
![image](https://user-images.githubusercontent.com/5502880/230662260-5da36537-3d06-4cd1-877e-d10217cac4fe.png)
![image](https://user-images.githubusercontent.com/5502880/230662392-1fefe8a2-7729-449a-a1ac-5d1dfc3f66cf.png)

### Device / Platform

Z4

**Comment by Karen-Intel** [comment]
Hi @zrmdsxa I'm going to help you too with the OBS issue
I will start debugging it on my end and get back to you in case I have questions

Thanks!

Karen

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa after performing a few experiments and doing some research, I've seen we have some reports already for OBS v.29. Have you tried streaming with OBS 28? Just curious, I have done the change specially in encoding and streaming and v28 works way better than 29 :)

Thanks!

**Comment by zrmdsxa** [comment]
OBS 28.1.1: Encoder error within 15 seconds of starting the battle on the map Northern Bridgehead in world of warplanes
![image](https://user-images.githubusercontent.com/5502880/231875509-db6fe58e-be62-49d5-8032-99171d59522d.png)

**Comment by Karen-Intel** [comment]
@zrmdsxa thank you! I will add OBS 28 to the existing reports. Have you observed this behavior with other games too or is it specific to World of Warplanes? 

Karen

**Comment by zrmdsxa** [comment]
It seems to be specific to world of warplanes. It hasn't happened to any other games so far

**Comment by Karen-Intel** [comment]
@zrmdsxa Thanks again
I will perform other experiments on other HW configurations and get back to you with my findings soon

Karen

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa sorry for the delay

I recreated the same settings in OBS and unfortunately I am unable to reproduce the encoder error. 
I was able to stream with  13900K +ARC 770 LE 16GB + driver v.4255 + OBS 28.0.3
I was playing World of Warplanes and didn't get any encoding error.
I wonder if you have tried[ DDU ](https://www.intel.com/content/www/us/en/support/articles/000091878/graphics.html)already when you performed the driver update?
It is recommended specially when we start seeing issues, and we do recommended as it is required for us to be able to reproduce any strange behavior to pursue and report any issue internally.

Please let me know 

Karen

**Comment by zrmdsxa** [comment]
I have run DDU and the encoder error still happens

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa no worries, thank you for confirming. 

We have some testing pending with an AMD system as in the Intel Desktop system we have not been able to reproduce, hopefully with this scenario  -closest to what you have - we will get more info.

Stay tuned.

Karen

**Comment by zrmdsxa** [comment]
Today I received this error after streaming Mindustry for 1 hour 43 minutes. I didn't have a problem in a previous stream where I streamed it for 6 hours

**Comment by Karen-Intel** [comment]
@zrmdsxa thank you for sharing! Did you use latest [DDU version ](https://www.wagnardsoft.com/forums/viewtopic.php?t=4491)and the latest GFX Driver release[ v4314](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html)e by any chance?
This information is very valuable to us as we have not been able to reproduce with World of Warplanes so far.
We're still debugging with World of Warplanes and will add Mindustry to the testing, we'll update this thread soon!

Karen

**Comment by zrmdsxa** [comment]
No I am still on 4255. I streamed Mindustry again and streamed 7 hours with no problem.



> Today I received this error after streaming Mindustry for 1 hour 43 minutes. I didn't have a problem in a previous stream where I streamed it for 6 hours

I also want  to mention at the start of that previous stream, my video on twitch looked like this and i had to stop and start the stream to fix it
![image](https://user-images.githubusercontent.com/5502880/235267272-11133b1e-6443-4205-880a-da67c4562ef8.png)

**Comment by Karen-Intel** [comment]
@zrmdsxa Hey, so you're not seeing the encoder issue anymore on OBS! That is great

FYI Arturo and I were performing some tests this morning. 
[He was streaming](https://www.twitch.tv/regulusalevica/video/1806022391) for about 2 hours with an A770 v.4314 and no encoder error/corruption happened, but we were running World of Warplanes, we haven't got to Mindustry yet and we are using the latest driver release. 

About the corruption, did it happen right after you started playing Mindustry?
Was it running in the background and if so, how long?

We have seen games crashing that get fixed with the latest DDU version, could you help us by upgrading your driver using it?
We still have in our bucket to test with Mindustry and if we are in the same "recipe" it will be more likely for us to reproduce this behavior too, please include all the details you recall so we can reproduce on our end, and thank you!

Karen

**Comment by zrmdsxa** [comment]
The corruption happened as soon as I started the stream.



I just ran DDU v18.0.6.3 and now it can't install Arc Control

**Comment by zrmdsxa** [comment]
a video of the corruption
https://user-images.githubusercontent.com/5502880/235281163-e70fda1e-5193-4a88-a813-50ed06ef42a0.mp4

**Comment by zrmdsxa** [comment]
Encoder error still happens with 4314

https://user-images.githubusercontent.com/5502880/235331880-a530db32-18ad-414c-b0de-84fa4cd48580.mp4

**Comment by Karen-Intel** [comment]
@zrmdsxa thank you for sharing your evidence.
We will try again to reproduce the issue, this time with OBS v29.
We'll get back with our findings soon :)

Karen

**Comment by zrmdsxa** [comment]
I am on 4314 and the video corruption happened when I streamed with OBS

https://user-images.githubusercontent.com/5502880/236666265-be2136ca-b964-4db4-9791-dd09d4efea0d.mp4

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa we were wondering if you have seen any improvement with the latest driver? 
We have not seen any other post related to this behavior and have not been able to reproduce.

Thank you

Karen

**Comment by zrmdsxa** [comment]
I will be able to check in 3 days when the world of warplanes event starts

**Comment by zrmdsxa** [comment]
Hello I did get the encoder error after streaming World of Warplanes for 2 hours and it happened on the map Plateau

**Comment by Karen-Intel** [comment]
Hey @zrmdsxa noted.
Proceeding to do some streaming tests, we will have an update this week in order to repro the error.

Talk to you soon

Karen

**Comment by zrmdsxa** [comment]
I streamed yesterday and had the encoder error during a battle in Plataeu, right after getting into a battle when it shows the map on Asian Border, and during a battle in Albion.
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/2e3a65a5-7323-4899-96e4-0a9fc0d93a56)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/7c6f4d35-28b4-4ba9-9c34-0d73c5cc3a2f)
![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/a43bdf6c-736d-46e7-9f22-411a753a74d3)

**Comment by zrmdsxa** [comment]
Today I streamed 1 hour and 39 minutes before the encoder error popped up in Road to Rome

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/07be8c36-5613-44d3-9846-4e5585f3a85e)

**Comment by Arturo-Intel** [comment]
@zrmdsxa besides OBS and the game, do you have any other software running when you are streaming?

**Comment by zrmdsxa** [comment]
Voicemeeter banana and VNyan

**Comment by zrmdsxa** [comment]
Error still happens with 4502

**Comment by zrmdsxa** [comment]
Error still happens with 4577

**Comment by zrmdsxa** [comment]
I just tried streaming Rune Factory 3 Special and got the OBS encoder error after streaming for 39 minutes

00:49:40.441: [qsv encoder: 'advanced_video_stream'] encode failed
00:49:40.441: Error encoding with encoder 'advanced_video_stream'
00:49:40.441: [rtmp stream: 'adv_stream'] Encoder error, disconnecting

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/bc21e1d1-0f80-4add-a9a5-79ad36dc624b)

**Comment by Joseph-Intel** [comment]
Hi @zrmdsxa I was able to test this with a very similar setup. I used OBS 29.1.3 and graphics driver V101.4826 and was able to stream Rune Factory 3 special for upwards of 2 hours with no issue. Would you be able to test again and let me know your results?

**Comment by zrmdsxa** [comment]
I'll let you know when I get a chance to stream those games again. 

https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/5502880/e57a8c13-8ee6-43a5-ab2f-709ac6d0467f


I did experience video corruption again though. OBS 29.1.2 and driver 4826. It's rare and randomly happens when you stream or record

**Comment by zrmdsxa** [comment]
I didn't have any problems in my 3 world of warplane streams of 4,4,8 hours this month.

**Comment by Arturo-Intel** [comment]
We can close this? @zrmdsxa

**Comment by Karen-Intel** [comment]
I think we can close this one. If symptom comes back, we can re-open

> I didn't have any problems in my 3 world of warplane streams of 4,4,8 hours this month.

@IGCIT please help us close :)

Karen

**Comment by zrmdsxa** [comment]
@Karen-Intel @Arturo-Intel Hello I just got the encoder error while streaming the game GTFO. I was able to stream for 13 minutes before it happened.

I am on driver 4952 and OBS 30.0.0
