### ISSUE TITLE
Star Wars : Jedi Survivor - Shadows Bugged/Game-breaking bug/Only Playable with Shadows set to Low

### ISSUE THREAD

**Issue by ABagOfPotato** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#297]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game / Application [Required]

Star Wars : Jedi Survivor

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

i5-11400

### Graphic Card [Required]

Arc A770 16GB

### GPU Driver Version [Required]

- [X] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [X] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[ssulog.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11358032/ssulog.txt)

### Description and steps to reproduce [Required]

Play the game at least one time on any Arc GPU.

You will notice that on the first level/mission/intro that things look quite dark. This is because the game ready driver does not appear to have been actually tested or optimised for the game.

Anyway that aside, please play through until the second mission/world/end of the introduction to the game.

As soon as you land on said world called 'Koboh' if you are running shadows at any setting above 'Low' with Ray Tracing turned 'Off' you will have black triangles and artifacting in pretty much all shadowed areas and the lighting will be incorrect.

If you turn on Ray Tracing with any level of shadow detail then areas of the map will be completely dark to the point you can't see anything at all.

Example: The area the player character spawns in when he lands is completely pitch black and you are unable to see anything at all if you turn around and face behind yourself.

Unfortunately I cannot post screenshots of this as I swapped to my AMD card to be able to play the game, I intended to swap back and take screenshots for this bug report but in changing my hardware back to Intel I got locked out of the game for 24 hours thanks to Denuvo.

If no one has confirmed this by the time it resets I will use one of my 'Activations' to post some screenshots of the bugs before I swap back to a playable card.

Edit: Several other users have reported the exact same issues on Reddit. This is a game wide issue and not just for one level, will potentially update when I can access the game again then will switch back to a different GPU to play.

P.S The included log is from my previous report as I currently have an AMD GPU installed.

### Game graphic quality [Required]

- [ ] Low
- [X] Medium
- [X] High
- [X] Ultra

### Game resolution [Required]

2560x1440

### Game VSync [Required]

On

### Game display mode [Required]

- [X] Fullscreen
- [ ] Windowed
- [X] Borderless Windowed

### Detailed game settings [Required]

Other settings don't impact.

Shadows = Medium/High/Epic 
Ray Tracing = Off
Result: Shadow artifacting all over the place, incorrect lighting.
---------------------------------------------------------------------
Shadows = Low/Medium/High/Epic 
Ray Tracing = On
Result: Pitch Black areas of the map with either no lighting whatsoever or incorrect lighting.
------------------------------------------------------------------------------------------------------
Shadows = Low
Ray Tracing = Off
Result: The only working graphics configuration currently on Intel Arc.

### Device / Platform name

Steam

**Comment by gargamel314** [comment]
Easily reproduceable! The problems all start on the Koboh part of the game. The first chapter of the game actually works very well, but the Koboh chapter gave me identical results with all settings bumped up to full. Only work-around was to turn ray tracing off and turn shadow quality down to low. Also, eventually the game would crash until I put it on these settings. `

**Comment by ABagOfPotato** [comment]
> Easily reproduceable! The problems all start on the Koboh part of the game. The first chapter of the game actually works very well, but the Koboh chapter gave me identical results with all settings bumped up to full. Only work-around was to turn ray tracing off and turn shadow quality down to low. Also, eventually the game would crash until I put it on these settings. `

Yeah..

I've removed some of the spicyness from my post in the hope they actually sort it out. They are lucky this has not been picked up by news outlets because it is completely unacceptable to put out a 'Game On' driver for the game when blatantly not testing or optimising for it whatsoever.

Totally understandable if they had not put the driver out, but in doing so they made a statement to everyone saying 'Look at how on the ball we are, here is a driver to make sure this new release is ready to be played' when in fact, I don't think they did anything at all, otherwise these game breaking issues would be obvious.

Which is odd because they compare the A750 to the 3060 in this game, where the 3060 does not have a game breaking bug, and where the settings they used literally don't work!

**Comment by ABagOfPotato** [comment]
This is what it looks like with Ray tracing 'Off' and shadows set to anything above low.
![Screenshot (30)](https://user-images.githubusercontent.com/5942191/235309348-d76bffd5-0400-4d48-ba9e-850958bb28c9.png)

If you turn on Ray Tracing then it looks like this.
![Screenshot (33)](https://user-images.githubusercontent.com/5942191/235309386-386ecc14-c5ac-4b38-97f7-5c360296706a.png)

Depending on the area entire sections of the game world can be like this.

The only workaround is to set shadows to low, at which point it looks like this.
![Screenshot (32)](https://user-images.githubusercontent.com/5942191/235309403-d0194173-8df9-4fc8-bd3d-aa01c15e81a6.png)

That said, I have still observed corruption in the shadows even on low, it's just that there are so few shadows that we are not having to see these massive bugs.

Someone from Intel care to comment on the 'Game On' driver?

Thanks,
Regards,
Former Customer

**Comment by lepusagri** [comment]
I have the same Problems

**Comment by evelyn-loves-coffee** [comment]
+1 - Also having same issue.

**Comment by Arturo-Intel** [comment]
Hello @ABagOfPotato , @gargamel314, @lepusagri  and @evelyn-loves-coffee 

We confirm the issue and the engineering team is working on it right now,

Just FYI for the fix to be released may take a while (3-6 months) so please keep your drivers up to date and do not close this post, 
I will keep you posted

-- r2

**Comment by gargamel314** [comment]
Thank you devs for all the hard work you do.

FYI I also submitted a bug report with EA at [this link here.](https://answers.ea.com/t5/Bug-Reports/Intel-Arc-A770-Shadows-and-Ray-Tracing-not-working-correctly/td-p/12525395)

**Comment by lepusagri** [comment]
3-6 month? Really? After that the gpu is out of date. Omg

**Comment by ABagOfPotato** [comment]
> 3-6 month? Really? After that the gpu is out of date. Omg

Yeah It's definitely frustrating, that said it seems to be the average response they give on here. Hopefully it's a pessimistic estimate and things get fixed sooner than that.

However they do have a lot of stuff to work on, like, a huge load of things, also remember Intel has been business focused for a long time, where they can stick to development lifecycles like this, compared to the gaming market where companies are quick to react with hotfix drivers etc when big problems happen.

Lets see what happens with time, but this is something we knew was a weak point with Arc going into it.

At least we know they know about it and that they are working on things :).

**Comment by Karen-Intel** [comment]
@lepusagri @ABagOfPotato we are very grateful with the community we have.

Every issue you raise is an opportunity for us to improve our products. 
Fixes will be applied not only for ARC, but also present and future Intel GFX products,
They actually take quite some time to be developed and implemented, so 3 to 6 months may seem like a long time, but be sure we're paying attention to each and every case you raise by reproducing it, debugging, following it up, which is of course doing our best to deliver Intel quality products :) 

We appreciate your patience in advance, will keep you posted

Karen

**Comment by ABagOfPotato** [comment]
> @lepusagri @ABagOfPotato we are very grateful with the community we have.
> 
> Every issue you raise is an opportunity for us to improve our products. Fixes will be applied not only for ARC, but also present and future Intel GFX products, They actually take quite some time to be developed and implemented, so 3 to 6 months may seem like a long time, but be sure we're paying attention to each and every case you raise by reproducing it, debugging, following it up, which is of course doing our best to deliver Intel quality products :)
> 
> We appreciate your patience in advance, will keep you posted
> 
> Karen

Thanks! We are very appreciative that you have this area to report things and communicate with users, there are not many opportunities to do this with other companies! Lets hope that things go well and we get to enjoy it as things progress!

I know there is a lot going on and a high workload with things still being so fresh. It's not like you've been able to go into this with years of drivers behind you already(for Arc).

Will keep this updated when I can as game patches come out and with new drivers!

Chris

**Comment by ArcAngel1984** [comment]
Erstmal vielen Dank für die tolle Arbeit, die ihr typen bei Intel macht.

Vorweg möchte ich sagen, dass die Raytracing Performance der ARC 770 16GB richtig gut ist. Sie liegt in Jedi Survivor gleichauf mit einer RX6800 mit der ich die ARC regelmäßig vergleiche.

Ich habe die gleichen Probleme in JEDI Survivor wie meine viele andere User hier auch. Teils sehr dunkle Areale im Spiel. Ich vermute das hat was mit den Einstellungen bei den Schatten zu tun.

Mein System
ASROCK x299 Taichi
Intel Core i7 7820X
32 GB DDR 4 Ram
Intel Arc A770 LE 16GB
Creative Soundblaser Z
BeQuiet 750W Netzteil
AOC 144Hz 27" Display (FreeSync) @ 1080p FHD

**Comment by gargamel314** [comment]
FYI I tried these features turned on when driver 4369 dropped, but it still wasn't working. Then EA released a new patch (patch 1.5). NOW raytracing is working just fine, and shadows seem to be working just fine on High settings (I haven't tried epic yet). Looks like the glitch was in the dev's implementation, not Intel's drivers.

**Comment by lepusagri** [comment]
Yeah! Perfect

**Comment by evelyn-loves-coffee** [comment]
Also confirming that Raytracing is fixed with latest game patch + latest WHQL Intel drivers, able to use Medium to High settings with no visual glitches.

**Comment by gargamel314** [comment]
> @gargamel314 that's great! @ABagOfPotato can you confirm this on your end? With this patch released by the game dev the game has improved in performance Please let us know! Thanks

Performance doesn't seem to have improved any since launch, but it wasn't a problem to begin with. With ray tracing I get 35-45 FPS at 1440p, but frames are buttery smooth, with no steering like the NVIDIA users have seen. Without raytracing with FSR turned on, I can get up to 90-110 FPS with the right settings. Of course I wish raytracing performance was faster, but there's not much to complain about. A couple clothing textures malfunction and go all over the screen, but that happens rarely. Haven't seen any performance increase after 4369 dropped, either.

**Comment by ArcAngel1984** [comment]
I can confirm that with the new Intel ARC driver 4369 and the game update to version 1.5, the vast majority of problems in connection with an Intel Arc graphics card and Jedi Survivor have been eliminated. Very rarely, small faulty textures or flickering shadows still occur. But you really have to look for them to notice them. Overall, I would describe the performance of the ARC A770 in Jedi Survivor with active raytracing as "above average".

**Comment by lepusagri** [comment]
Sometimes i can see white areas when I rotate fast. Seems like the card is not fast enough to load in the textures.
