### ISSUE TITLE
Blender crashes when toggling between rendered shading with Cycles, and doing some other things

### ISSUE THREAD

**Issue by a-One-Fan** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#367]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

Blender 3.6 LTS

### Processor / Processor Number [Required]

Ryzen 7 3700x

### Graphic Card [Required]

Arc A770 LE 16GB

### GPU Driver Version [Required]

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/18682c8f-fac4-4bc8-8064-4d7c93b8ad4d)

- [X] 31.0.101.4502
- [ ] 31.0.101.4499
- [ ] 31.0.101.4382
- [ ] 31.0.101.4369
- [ ] 31.0.101.4335
- [ ] 31.0.101.4314
- [ ] 31.0.101.4311
- [ ] 31.0.101.4257
- [ ] 31.0.101.4255
- [ ] 31.0.101.4148
- [ ] 31.0.101.4146
- [ ] 31.0.101.4125
- [ ] 31.0.101.4123
- [ ] 31.0.101.4091
- [ ] 31.0.101.4090
- [ ] 31.0.101.4034
- [ ] 31.0.101.4032
- [ ] 31.0.101.3975

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build Number [Required]

- [X] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu_4514.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11889632/igcit_ssu_4514.txt)
[igcit_ssu_4502.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11889631/igcit_ssu_4502.txt)

### Description and steps to reproduce [Required]

As the crash log notes `embree4.dll` as the culprit, this is likely the place for this issue.

Blend file: 
[crash_blend.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11889479/crash_blend.txt)
This is not a text file; rename it back to .blend because (this?) Github (repo?) doesn't like .blend files.

![image](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/100067309/f6cb9228-c5d2-4ca3-92be-ed952111b505)

This is a bit of a doozy to describe into words, so have a video where I replicate this ~7 times in a row: 
https://www.youtube.com/watch?v=kXJGvuYAKso (recorded with 4514)
https://www.youtube.com/watch?v=Y37MLoH6ehQ (recorded with 4502)

Enable the shading pie menu for convenience  - Edit > Preferences > Addons > Interface: 3D Viewport pie menus > Shading pie. Have 2 viewports open. Set the top to rendered shading. Rapidly toggle between rendered shading, shading an object flat/smooth and non-rendered shading. Don't be too accurate with what you toggle between. Eventually, Blender should crash.

### Crash dumps [Required, if applicable]

I couldn't find any dumps after looking in the few locations. IGCIT couldn't generate its archive (presumably because no dumps) :(
Sorry

### Application / Windows logs

[blender_debug_output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11889421/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/11889422/blender_system_info.txt)

**Comment by Karen-Intel** [comment]
@a-One-Fan thank you for your submission!

Just in time to add this additional info in my internal report + thank you for testing with the latest driver.

I will keep you posted on progress! Have a great day!

Karen

**Comment by ph0b** [comment]
Hi, I believe it's the same issue as reported here: https://projects.blender.org/blender/blender/issues/109771#issuecomment-980140 - can you try to repro with 4.0 that has the fix, or with 3.6 + embree4.dll shared from this comment ? https://projects.blender.org/blender/blender/issues/109771#issuecomment-977150

**Comment by Karen-Intel** [comment]
Hey @ph0b thank you for tghe heads up!
@a-One-Fan I can confirm that after a few test toggling between drawing the scene in wireframe and solid mode the app does not crash using blender v.4.0 Alpha w/driver 4575 WHQL
Could you check on your end? Thanks

Karen

**Comment by a-One-Fan** [comment]
Hey @ph0b , I was having more general crashes that would happen around the time I toggled rendered shading, similar to what's described in the issue you linked. However, with this description, it's a pretty unactionable issue, so I sat down and found this specific way here to reproduce crashing.

The crashing has been greatly improved. It's not completely resolved, however.
Like @Karen-Intel I also had more trouble reproducing it, but tougher issues require tougher methods to reproduce, and bumping up the number of viewports has helped me reproduce it.

Here's a new version of the crashy blend file:
[crash_blend.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175747/crash_blend.txt)

Crashes now point to different things. Most commonly they point to `VCRUNTIME140.dll`, however I got crashes decently commonly in `igxehpgicd64.dll` and I managed to score another in embree4 again.

[blender_debug_output_embree.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175779/blender_debug_output_embree.txt)
[blender_debug_output_ig.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175785/blender_debug_output_ig.txt)
[blender_debug_output_vcruntime.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175787/blender_debug_output_vcruntime.txt)

[blender_system_info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175836/blender_system_info.txt)
[igcit_ssu_4576.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12175834/igcit_ssu_4576.txt)

I did my testing with the 4576 driver that showed up recently, and with Blender 4.0 hash `aebc743bf1c7`.

**Comment by ph0b** [comment]
Stability of 4.0 may be impacted by this bug : https://projects.blender.org/blender/blender/issues/109282 when using embree. until the fix is available in a next driver, you may want to test stability with it disabled.

**Comment by a-One-Fan** [comment]
@ph0b

[crash_blend.crash_embree.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12176490/crash_blend.crash_embree.txt)
[crash_blend.crash_vcruntime.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12176493/crash_blend.crash_vcruntime.txt)
[crash_blend.crash_igxe.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12176495/crash_blend.crash_igxe.txt)

**Comment by Karen-Intel** [comment]
@a-One-Fan have you tested if this behavior is still reproducible with our driver v.4887? Please let us know

Karen

**Comment by a-One-Fan** [comment]
@Karen-Intel Sorry, I can still reproduce it.

[blender_debug_output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12952010/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12952013/blender_system_info.txt)

[crash_blend2.crash.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/12952146/crash_blend2.crash.txt)

**Comment by Karen-Intel** [comment]
Hey @a-One-Fan  just sharing the internal report number about this issue :) 14020694502
Our dev team is already working on it, once we get an update will post it in this thread

Karen

**Comment by Karen-Intel** [comment]
Hey @a-One-Fan I just tried rapidly toggling between rendered shading, shading an object flat/smooth and non-rendered shading about 100 times and Blender hasn't crashed for me.
Could you verify with [latest driver ](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html) please? TY

Karen

**Comment by a-One-Fan** [comment]
@Karen-Intel Sorry for the delay. I can still reproduce:

[crash_blend2.crash.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14157943/crash_blend2.crash.txt)
[blender_debug_output.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14157945/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14157946/blender_system_info.txt)
[igcit_ssu_5186.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/14157948/igcit_ssu_5186.txt)

**Comment by rmorera-intel** [comment]
Hi @a-One-Fan please install driver [32.0.101.6078](https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html). I was told by debug the fix should be included in it.

Best Regards,
Ronald M.

**Comment by rmorera-intel** [comment]
I didn't hear back so I'll close this one. If the issue re-appears feel free to re-open this bug.
