### ISSUE TITLE
Low FPS in Risen 3

### ISSUE THREAD

**Issue by Dawidusergit** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#770]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Game is not cracked, modded and use the latest patch

### Game [Required]

Risen 3: Titan Lords

### Game Platform [Required]

- [X] Steam
- [ ] Microsoft Store
- [ ] GOG Galaxy
- [ ] Ubisoft Connect
- [ ] Battle.net
- [ ] Epic Games
- [ ] Rockstar Games Launcher
- [ ] EA app
- [ ] Amazon Games app
- [ ] Other (please specify)

### Processor / Processor Number [Required]

Ryzen 5600

### Graphic Card [Required]

ARC A770 16GB

### GPU Driver Version [Required]

31.0.101.5444

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [X] DirectX9

### Windows Build Number [Required]

- [X] Windows 11 23H2
- [ ] Windows 11 22H2
- [ ] Windows 11 21H2
- [ ] Windows 10 22H2
- [ ] Windows 10 21H2
- [ ] Other (Please specify)

### Intel System Support Utility report

[igcit_ssu.txt](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15048692/igcit_ssu.txt)

### Description and steps to reproduce [Required]

Low Gpu/Cpu utilization and low FPS, around 35-38 FPS on Ultra settings. Using the Alt Tab combination crashing the game.
![ss risen3](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/167009330/02b1588c-67ff-40d2-a4bb-d59dd8bc2c77)

### Game graphic quality [Required]

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Ultra

### Game resolution [Required]

1920x1080

### Game VSync [Required]

Off

### Game display mode [Required]

- [X] Fullscreen
- [X] Windowed
- [ ] Borderless Windowed

### Detailed game settings [Required]

![settingsrisen3 2](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/167009330/495ee84e-af88-4948-bb76-77c92bd42057)
![settingsrisen3](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/assets/167009330/ac634b30-7d86-47c3-82f6-ddb56c5d98a6)

### Save game

[SaveData_0025.zip](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/files/15048704/SaveData_0025.zip)

**Comment by Vivek-Intel** [comment]
@Dawidusergit Thanks for reporting the issue. we are looking into the issue and let you know the updates.

**Comment by Vivek-Intel** [comment]
We have escalated the crash when Alt+Tab issue with Engineering team. internal id for reference - 16024059462

**Comment by SavageWaffle** [comment]
Is this solved?

**Comment by Dawidusergit** [comment]
Yes, but not perfect. After Alt+Tab and return to game for 2-3 seconds game working in few fps. Later start working fine. On nvidia works fine and return from desktop much faster.

**Comment by SavageWaffle** [comment]
Crashing resolved, remaining issues likely overhead related and root cause analysis is underway for that with fix TBD across multiple titles.

**Comment by Arturo-Intel** [comment]
@SavageWaffle Can I ask, who are you?  You are not the OP nor an Intel employee.
Why are you misinforming the OP with false case status?

**Comment by SavageWaffle** [comment]
@Arturo-Intel  OP stated crashing was resolved? I went through all the open tickets to update their status based off last comments, they usually fall into two bucks of "Can be marked as closed/resolved" or "Fix TBD". There was a good 10+ tickets that had been solved yet never closed as such. Other tickets got updates from users that they were still seeing an issue and or that issue resolution is still underway based off last case notes. For this ticket specifically a fix appears TBD as it is under investigation?

**Comment by Arturo-Intel** [comment]
@SavageWaffle 

Most of the cases were as they were for internal reasons that I don't think you're aware of. (although I admit there were a bunch that had already been fixed and weren't reflected in the github cases).

You still haven't answered whether you're an Intel employee or not; if you're not, avoid sharing your status categories in the cases, you're confusing the OP with your unofficial categorization.
If you are, please contact me to have a 1:1 chat and get up to speed on the internal process.

We're working hard to provide the OP with a solution to their problems and it takes time, and I'm not just referring to this particular case.
If you have something to share for the benefit of the case, do so, but don't pressure the team with your open questions (is this done?, has it been resolved?, etc). Don't ask the admin to close cases (only the OP and Intel employees can ask for this) or promise fixes that you have no idea about.

I understand that you're doing this for the benefit of the community, but spamming open questions, giving false status to cases, promising fixes, etc. is not helpful in the slightest.

-- r2

**Comment by SavageWaffle** [comment]
@Arturo-Intel Was not my intent to confuse people.

**Comment by Felipe-Intel** [comment]
The crash issue is a known issue on Arc A-Series. Please check [this article](https://www.intel.com/content/www/us/en/support/articles/000098818.html) for any change in this situation.
The low performance issue is still under investigation.

**Comment by Zack-Intel** [comment]
Hello,

Thank you for reporting this issue. Our priority is to target the most popular games and apps to focus our efforts on providing a high quality, stable experience for the broadest set of users. We will continue to improve our software performance and compatibility throughout 2025 and beyond. While we can’t accommodate your request at this time, please watch [this article](https://www.intel.com/content/www/us/en/support/articles/000100683/graphics.html) on our website for any possible changes to this situation.
