### ISSUE TITLE
intel Graphics Software reporting incorrect System RAM Speed

### ISSUE THREAD

**Issue by Susie1818** [IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT#897]
### Checklist [README]

- [X] Device is not undervolted nor overclocked
- [X] Device is using the [latest drivers](https://github.com/IGCIT/Intel-GPU-Community-Issue-Tracker-IGCIT/wiki/Intel-driver-updates-and-changelogs)
- [X] Application is not cracked, modded and use the latest patch

### Application [Required]

intel Graphics Software

### Processor / Processor Number [Required]

intel Core i7-13700KF

### Graphic Card [Required]

intel Arc B580

### GPU Driver Version [Required]

32.0.101.6325_101.6252

### Rendering API [Required]

- [ ] Vulkan
- [ ] OpenGL
- [ ] DirectX12
- [ ] DirectX11
- [ ] DirectX10
- [ ] DirectX9
- [X] Not applicable

### Windows Build [Required]

Windows 11 23H2

### Intel System Support Utility report

[SSU_20241218.txt](https://github.com/user-attachments/files/18170744/SSU_20241218.txt)

### Description and steps to reproduce [Required]

![Screenshot (35)](https://github.com/user-attachments/assets/6406b9bc-a7e4-46e4-b8d4-e7401b654e96)

My system RAM speed is 3600, but the new intel Graphics Software incorrectly reports 2133.

**Comment by Ilya-intel** [comment]
Hi @Susie1818 ,
The issue has been filed under bug id 13012617627.
I'll keep you updated in this thread.
Thanks for reporting.

**Comment by CasteloAdrian** [comment]
IGS is not reporting incorrectly, it's reporting in a different unit value. Task manager is reporting in MT/s while IGS is reporting in MHz. Given there is a recent push from industry to move to MT/s vs previously standard MHz we will look at changing what we report in IGS but the value in MHz is not 'wrong'.

**Comment by Susie1818** [comment]
What the ....

Even if you want to report MHz instead of MT/s, it should be 1800 MHz, not 2133. Why are you muddying the waters and misleading people?

**Comment by IGCIT** [comment]
@Susie1818 please avoid aggressive replies.
i already warned you months ago, and your recent messages, once again, are too aggressive and irrespectul.
if you don't agree with someone or find the answer is not correct, explain your points politely and be respectful.

**Comment by CasteloAdrian** [comment]
I'll just try to help clear up a little more on my reply to be helpful then will leave it at that. My comment was hopefully helping to highlight that there is a difference in unit reporting here if it was missed and what our direction would be to help resolve this for users (moving to MT/s instead). For right/wrong on current reporting on DDR5 it might help to provide the information that IGS itself does not calculate any of this information, we pull it directly from the OS. It's possible MS is not calculating MHz correctly on DDR5 yes, but from our POV we are going to have to assume the OS is doing it's calculations correctly. I hope that helps.

**Comment by Susie1818** [comment]
@IGCIT 

I can understand that it is not your responsibility to verify the correctness of each and every comment since you are the moderator, not one of the engineers who are responsible for solving the issues. I can understand that if I were the moderator, I am not able to discern which comments are correct and which comments are not, either. 

I don't know what the best way for people to express themselves is nowadays. There is no real penalty when we leave some misinformation in our comments. Maybe it's a value that we just protect people's right of speech regardless of the correctness of the information because the history told us the consequences when the authorities could restrict people's speech in the name of correctness that was actually artificially manipulated.

I am not the God, and I can understand that I might unintentionally leave misinformation in my own comments as well.

Nevertheless, I do hope this forum is a place solely focusing on debugging intel's graphics products with as little misinformation as possible.

**Comment by Susie1818** [comment]
@CasteloAdrian 

Your "help" only makes sense if it were 1800 MHz when I started this ticket.

I don't know who you are referring to as "we". Are you the engineer who wrote the code to display the readings in question? Apparently not. Please don't leave comments here out of your imagination.

In your comment, you mentioned DDR5. Firstly, DDR5-3600 does not exist. The lowest spec'd speed in the industry for DDR5 is 4000, and the actual lowest spec'd product you can buy on the market is DDR5-4800. Using the term DDR5 in the context makes you look unprofessional here. Secondly, in the screenshot I posted, the intel Graphics Software already displayed "System RAM Type" as DDR4. Using the term DDR5 in the context makes you look careless and inconsiderate here.

As a software engineer myself, I need to tell you that if you want to retrieve a value from a third-party API, it is your responsibility to verify whether it's usable or not, otherwise you write your own code to do the job. You can't have the cake and eat it at the same time. You cannot just shift the blame saying "we are going to have to assume the OS is doing its calculations correctly."

**Comment by SavageWaffle** [comment]
I believe this is solved. For example, my memory is running 6000Mhz XMP and IGS reports that accurately. Windows TM also reports the expected 6000M/T's. M/T vs Mhz is really not an issue as I see no in correct reporting of the actual run rate of the memory.

**Comment by Susie1818** [comment]
I'll check it again later when I am off work.

**Comment by SavageWaffle** [comment]
@Susie1818 please let us know if issue persists

**Comment by Susie1818** [comment]
Yes, the issue persists with the latest intel Graphics Software version 24.50.1001.1.

It's not a difficult problem. Both CPU-Z and HWiNFO can report the correct memory speed (1800MHz).

**Comment by SavageWaffle** [comment]
@Susie1818 @Felipe-Intel You want the clock cycle speed to be shown vs what they currently show is the data rate, which mimics the windows task manager as of 24H2. Changing it be the clock cycle speed while technically more accurate would likely confuse normal people. I understand the desire but I just wouldn’t get my hopes up for them to make that change.

**Comment by Ilya-intel** [comment]
@Susie1818 this issue is not included in the driver package yet, but you can expect the fix to be published soon.
FYI @SavageWaffle

**Comment by Susie1818** [comment]
@SavageWaffle 

I don't care which unit it uses AT ALL. Either MT/s or MHz is fine. What's important is that the number has to be CORRECT.

<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/fae313ba-29c1-4065-888b-0c518479eb2f" />

**Comment by SavageWaffle** [comment]
@Susie1818 Wild, glad a fix is incoming!

**Comment by Ilya-intel** [comment]
Hey @Susie1818 ,
Could you install the latest 32.0.101.6557 driver and check RAM speed in the IGS?

**Comment by Susie1818** [comment]
@Ilya-intel 

You should not have asked me to install the latest 32.0.101.6557 driver because the IGS included in this update has already been known very buggy from other tickets. Nevertheless, I did as you requested and installed it.

Basically, the IGS wouldn't open after this update. You have to stop the IntelGraphicsSoftwareService in the Windows Services first so that the IGS app can launch. And then, after it is launched, a lot of readings in the metrics section are gone, showing N/A. More importantly, the Tuning tab just disappeared. The workaround is that you need to restart the IntelGraphicsSoftwareService and then the Tuning tab would reappear. However, even so, the Tuning feature becomes useless because next time you reboot your PC, the IGS does not launch before you stop the IntelGraphicsSoftwareService first, and after you repeat the same procedures mentioned above, the IGS thinks something went wrong because the IntelGraphicsSoftwareService is not running, so it wouldn't keep your settings.

Lastly, the ironic good news is that the latest IGS 25.2.1055.2 does show the RAM speed correctly, but it took me so much unnecessary trouble to give you this confirmation. Basically, I could have just uninstalled this buggy update as soon as I found that I could not open the IGS right after I installed it, and then you and I would not know if this RAM speed thing is fixed or not in the first place. And in fact, I have to uninstall it right now and roll back to an earlier driver anyway because it is useless in this state.

![Image](https://github.com/user-attachments/assets/002281f5-6b1e-4db1-b807-6d7da16b5359)

**Comment by Susie1818** [comment]
@Ilya-intel 

Do NOT close this ticket before an actally usable version of IGS is released later. Thank you.

**Comment by Susie1818** [comment]
@Ilya-intel 

IGS version 25.6.1152.1 (bundled in driver 101.6632) has fixed the "can't open IGS" bug.

This ticket can be closed. Thank you.
